version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/nightwolf93/brisk
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -v -t -d ./...
      - run: go build -o ./bin/brisk
      - run: docker build -t nightwolf93/brisk:$CIRCLE_BRANCH .