version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/nightwolf93/brisk
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -v -t -d ./...
      - run: go build -o ./bin/brisk
      - run: docker build -t nightwolf93/brisk:$CIRCLE_BRANCH .
      - run: docker tag nightwolf93/brisk:$CIRCLE_BRANCH cloud.canister.io:5000/nightwolf93/brisk:$CIRCLE_BRANCH
      - run: docker tag nightwolf93/brisk:$CIRCLE_BRANCH nightwolf931/brisk:$CIRCLE_BRANCH
      - run: docker login --username=$CANISTER_ID --password=$CANISTER_PASS cloud.canister.io:5000
      - run: docker login --username=$DOCKERHUB_USERNAME --password=$DOCKERHUB_PASS
      - run: docker push cloud.canister.io:5000/nightwolf93/brisk:$CIRCLE_BRANCH
      - run: docker push nightwolf931/brisk:$CIRCLE_BRANCH