version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/nightwolf93/brisk
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -v -t -d ./...
      - run: go test ./...
      - run: go build -o ./bin/brisk
      - run: docker build -t nightwolf93/brisk:$CIRCLE_BRANCH .
      - run: docker tag nightwolf93/brisk:$CIRCLE_BRANCH nightwolf931/brisk:latest
      - run: docker login --username=$DOCKERHUB_USERNAME --password=$DOCKERHUB_PASS
      - run: docker push nightwolf931/brisk:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
